### ISSUE TITLE
fx_arbitrage sequence diagrams

### ISSUE THREAD

**Issue by nperincherry** [FinancialMarkets/5MinuteFinance#2]
There should be arrows in direction of flow in the sequence diagrams on slides 6, 13 and 17

**Comment by Matt-Brigida** [comment]
This is fixed in the development version of DiagrammeR:  `devtools::install_github('rich-iannone/DiagrammeR')`

Will leave this issue open until it is pushed to CRAN.

**Comment by Matt-Brigida** [comment]
Works now!
